def format_pr_comment(repo: str, graph):
    if not graph.findings:
        return None

    high = [f for f in graph.findings if f.severity == "high"]
    medium = [f for f in graph.findings if f.severity == "medium"]

    top_findings = graph.findings[:5]

    lines = [
        "## Invisible Pipeline CI/CD Risk Report",
        "",
        f"Repository: `{repo}`",
        "",
        f"Findings: **{len(graph.findings)}**",
        f"High severity: **{len(high)}**",
        f"Medium severity: **{len(medium)}**",
        "",
        "### Top findings",
    ]

    for finding in top_findings:
        lines.append(
            f"- **{finding.severity.upper()}**: {finding.title}  \n"
            f"  {finding.description}"
        )

    lines.extend(
        [
            "",
            "### Recommended next step",
            "Review the flagged workflow steps and pin GitHub Actions to full commit SHAs where possible.",
            "",
            "_Generated by Invisible Pipeline._",
        ]
    )

    return "\n".join(lines)
